// This file is autogenerated by the hyperschema compiler
// Schema Version: 2
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 2

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @broadcast/payload.payload
const encoding0_1 = c.array(c.buffer)

// @broadcast/payload
const encoding0 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.publicKey)
    encoding0_1.preencode(state, m.payload)
  },
  encode(state, m) {
    c.fixed32.encode(state, m.publicKey)
    encoding0_1.encode(state, m.payload)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)
    const r1 = encoding0_1.decode(state)

    return {
      publicKey: r0,
      payload: r1
    }
  }
}

// @broadcast/pointer
const encoding1 = {
  preencode(state, m) {
    c.uint.preencode(state, m.to)
    c.uint.preencode(state, m.from)
    c.buffer.preencode(state, m.nonce)
    c.buffer.preencode(state, m.buffer)
  },
  encode(state, m) {
    c.uint.encode(state, m.to)
    c.uint.encode(state, m.from)
    c.buffer.encode(state, m.nonce)
    c.buffer.encode(state, m.buffer)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.buffer.decode(state)

    return {
      to: r0,
      from: r1,
      nonce: r2,
      buffer: r3
    }
  }
}

// @broadcast/message.payload
const encoding2_1 = c.frame(encoding0)
// @broadcast/message.pointer
const encoding2_2 = c.frame(encoding1)

// @broadcast/message
const encoding2 = {
  preencode(state, m) {
    c.uint.preencode(state, m.version)
    state.end++ // max flag is 2 so always one byte

    if (m.payload) encoding2_1.preencode(state, m.payload)
    if (m.pointer) encoding2_2.preencode(state, m.pointer)
  },
  encode(state, m) {
    const flags = (m.payload ? 1 : 0) | (m.pointer ? 2 : 0)

    c.uint.encode(state, m.version)
    c.uint.encode(state, flags)

    if (m.payload) encoding2_1.encode(state, m.payload)
    if (m.pointer) encoding2_2.encode(state, m.pointer)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      version: r0,
      payload: (flags & 1) !== 0 ? encoding2_1.decode(state) : null,
      pointer: (flags & 2) !== 0 ? encoding2_2.decode(state) : null
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@broadcast/payload':
      return encoding0
    case '@broadcast/pointer':
      return encoding1
    case '@broadcast/message':
      return encoding2
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
